artifact_uri: /home/ubuntu/tai/runs/mlflow/627022464411347413/eb3c1601eaea4f3889d309c0a3fe85a8/artifacts
end_time: null
entry_point_name: ''
experiment_id: '627022464411347413'
lifecycle_stage: active
run_id: eb3c1601eaea4f3889d309c0a3fe85a8
run_name: task1
source_name: ''
source_type: 4
source_version: ''
start_time: 1779477800447
status: 1
tags: []
user_id: team3
