artifact_location: /home/ubuntu/tai/runs/mlflow/0
creation_time: 1779445823474
experiment_id: '0'
last_update_time: 1779445823474
lifecycle_stage: active
name: Default
trace_location: null
workspace: default
