artifact_location: /home/ubuntu/tai/runs/mlflow/627022464411347413
creation_time: 1779445823537
experiment_id: '627022464411347413'
last_update_time: 1779445823537
lifecycle_stage: active
name: /home/ubuntu/tai/runs/detect
trace_location: null
workspace: default
